main:
  test: test

# H2 in memory configuration
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  # url localhost:8080/h2
  h2:
    console:
      enabled: true
      path: /h2



